name: print
on:
  push:
    branches:
      - lejan/second
jobs:
  first:
    runs-on: ubuntu-latest
    name: onlyprint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'master'
    - run: cat README.md
