name: print
on:
  push:
    branches:
      - main
jobs:
  first:
    runs-on: ubuntu-latest
    name: onlyprint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: cat README.md
