name: print
on:
  push:
    branches:
      - lejan/second
jobs:
  first:
    runs-on: ubuntu-latest
    name: onlyprint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - run: cat README.md
    - run: echo 'hello world'
      if: ${{0}}
    - run: echo 'bye'
